### ISSUE TITLE
Remove Potion Particles 

### ISSUE THREAD

**Issue by Giganticookie** [whwdzg/Glowing_Players#2]
Editing the glow.mcfunction file to add "0 true" to the end will remove the yellow potion particle effects given to the player by the glow effect. This will keep the glow just remove the particles.

Current:   effect give @a glowing infinite
Edit:         effect give @a glowing infinite 0 true

I've tested this myself and can confirm it works, given you clear the glowing effect before enabling.

**Comment by whwdzg** [comment]
thanks for your advice! I'll update it soon!

**Comment by whwdzg** [comment]
Finished in 1.0.2
